# -*- coding: utf-8 -*-
"""Klasifikasi ELM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0xOE4U1i-KcEm_Pm2Y62YdCJWO11GYF
"""

import numpy as np


def elm_fit(X, target, h, W=None):
    if W is None:
        W = np.random.uniform(-.6, .6, (h, len(X[0])))

    print('Hinit')
    Hinit = X @ W.T
    print(Hinit)
    print('H')
    H = 1 / (1 + np.exp(-Hinit))
    print(H)
    Ht = H.T
    print('H+')
    Hp = np.linalg.inv(Ht @ H) @ Ht
    print(Hp)
    print('beta')
    beta = Hp @ target
    print(beta)
    print('y')
    y = H @ beta
    print(y)
    mape = sum(abs(y - target) / target) * 100 / len(target)

    return W, beta, mape

def elm_predict(X, W, b, round_output=False):
    Hinit = X @ W.T
    H = 1 / (1 + np.exp(-Hinit))
    y = H @ b

    if round_output:
        y = [int(round(x)) for x in y]

    return y

import pandas as pd
from sklearn.preprocessing import minmax_scale

# Memuat data dari file CSV menggunakan Pandas
df = pd.read_csv('ELM.csv')
delcolum = ['Tanggal','Wilayah','Critical','Max']
df = df.drop(delcolum, axis=1)
df.head()

import matplotlib.pyplot as plt

df_subset = df.head(1)  # Memilih 10 baris pertama

# Menampilkan bar chart dari subset data
df_subset.plot(kind='bar')
plt.xlabel('Index Data')
plt.ylabel('Value')
plt.title('Bar Chart (Subset)')
plt.show()

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import accuracy_score


# Mengambil fitur dari DataFrame
X = df.iloc[:, :-1].values

# Mengambil target dari DataFrame
Y = df.iloc[:, -1].values

# Melakukan normalisasi Min-Max pada fitur
X = minmax_scale(X)



X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=.3)
W, b, mape = elm_fit(X_train, y_train, 5)

print('MAPE:', mape)

predict = elm_predict(X_test, W, b, round_output=True)
accuracy = accuracy_score(predict, y_test)

print('Output:', predict)
print('True  :', y_test)
print('Accuracy:', accuracy)